### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by varunmamtora06** [varunmamtora06/devops_notes#4]
## Following are the topics to be covered
- [x] Intro to devops
- [x] Comparision of devops with other methods with analogies
- [ ] linux commands
- [ ] git commands
- [ ] AWS stuff(maybe)
- [ ] Docker
- [ ] Jenkins
- [ ] Kubernetes
